# Generated by Django 4.1.5 on 2023-02-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuserprofile',
            name='firstName',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='myuserprofile',
            name='lastName',
            field=models.CharField(default='', max_length=250),
        ),
    ]
