# Generated by Django 4.1.5 on 2023-02-20 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_otpmodel_otp_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='otp_myuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
