# Generated by Django 4.1.5 on 2023-02-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_otpmodel_otp_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
